export const SuburbDetail = {
    "rows": [
        {"key": "ABBOTSFORD", "value": [{"pos": 2, "neg": 0, "neu": 2, "suburb": "ABBOTSFORD"}]},
        {"key": "ALBERT PARK", "value": [{"pos": 2, "neg": 0, "neu": 6, "suburb": "ALBERT PARK"}]},
        {"key": "ALPHINGTON", "value": [{"pos": 2, "neg": 0, "neu": 0, "suburb": "ALPHINGTON"}]},
        {"key": "ALTONA", "value": [{"pos": 2, "neg": 0, "neu": 1, "suburb": "ALTONA"}]},
        {"key": "ALTONA MEADOWS", "value": [{"pos": 3, "neg": 0, "neu": 4, "suburb": "ALTONA MEADOWS"}]},
        {"key": "ALTONA NORTH", "value": [{"pos": 1, "neg": 2, "neu": 3, "suburb": "ALTONA NORTH"}]},
        {"key": "ARMADALE", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "ARMADALE"}]},
        {"key": "ASCOT VALE", "value": [{"pos": 1, "neg": 0, "neu": 3, "suburb": "ASCOT VALE"}]},
        {"key": "ASHBURTON", "value": [{"pos": 2, "neg": 0, "neu": 5, "suburb": "ASHBURTON"}]},
        {"key": "ASHWOOD", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "ASHWOOD"}]},
        {"key": "ASPENDALE", "value": [{"pos": 0, "neg": 1, "neu": 0, "suburb": "ASPENDALE"}]},
        {"key": "BALWYN", "value": [{"pos": 2, "neg": 0, "neu": 5, "suburb": "BALWYN"}]},
        {"key": "BAYSWATER", "value": [{"pos": 2, "neg": 2, "neu": 0, "suburb": "BAYSWATER"}]},
        {"key": "BEAUMARIS", "value": [{"pos": 2, "neg": 1, "neu": 7, "suburb": "BEAUMARIS"}]},
        {"key": "BELGRAVE", "value": [{"pos": 0, "neg": 1, "neu": 0, "suburb": "BELGRAVE"}]},
        {"key": "BELGRAVE SOUTH", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "BELGRAVE SOUTH"}]},
        {"key": "BENTLEIGH", "value": [{"pos": 3, "neg": 4, "neu": 7, "suburb": "BENTLEIGH"}]},
        {"key": "BENTLEIGH EAST", "value": [{"pos": 4, "neg": 2, "neu": 7, "suburb": "BENTLEIGH EAST"}]},
        {"key": "BERWICK", "value": [{"pos": 5, "neg": 0, "neu": 2, "suburb": "BERWICK"}]},
        {"key": "BLACK ROCK", "value": [{"pos": 1, "neg": 1, "neu": 1, "suburb": "BLACK ROCK"}]},
        {"key": "BLACKBURN", "value": [{"pos": 2, "neg": 0, "neu": 1, "suburb": "BLACKBURN"}]},
        {"key": "BLAIRGOWRIE", "value": [{"pos": 0, "neg": 0, "neu": 3, "suburb": "BLAIRGOWRIE"}]},
        {"key": "BONBEACH", "value": [{"pos": 0, "neg": 1, "neu": 2, "suburb": "BONBEACH"}]},
        {"key": "BORONIA", "value": [{"pos": 1, "neg": 0, "neu": 2, "suburb": "BORONIA"}]},
        {"key": "BOTANIC RIDGE", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "BOTANIC RIDGE"}]},
        {"key": "BOX HILL", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "BOX HILL"}]},
        {"key": "BOX HILL NORTH", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "BOX HILL NORTH"}]},
        {"key": "BOX HILL SOUTH", "value": [{"pos": 2, "neg": 0, "neu": 3, "suburb": "BOX HILL SOUTH"}]},
        {"key": "BRAESIDE", "value": [{"pos": 3, "neg": 1, "neu": 2, "suburb": "BRAESIDE"}]},
        {"key": "BRIGHTON", "value": [{"pos": 1, "neg": 1, "neu": 5, "suburb": "BRIGHTON"}]},
        {"key": "BRIGHTON EAST", "value": [{"pos": 4, "neg": 1, "neu": 9, "suburb": "BRIGHTON EAST"}]},
        {"key": "BROOKLYN", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "BROOKLYN"}]},
        {"key": "BRUNSWICK", "value": [{"pos": 6, "neg": 2, "neu": 14, "suburb": "BRUNSWICK"}]},
        {"key": "BRUNSWICK EAST", "value": [{"pos": 7, "neg": 2, "neu": 14, "suburb": "BRUNSWICK EAST"}]},
        {"key": "BRUNSWICK WEST", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "BRUNSWICK WEST"}]},
        {"key": "BUNDOORA", "value": [{"pos": 0, "neg": 0, "neu": 4, "suburb": "BUNDOORA"}]},
        {"key": "BURNSIDE", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "BURNSIDE"}]},
        {"key": "BURWOOD", "value": [{"pos": 3, "neg": 0, "neu": 0, "suburb": "BURWOOD"}]},
        {"key": "BURWOOD EAST", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "BURWOOD EAST"}]},
        {"key": "CAMBERWELL", "value": [{"pos": 1, "neg": 0, "neu": 1, "suburb": "CAMBERWELL"}]},
        {"key": "CAMPBELLFIELD", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "CAMPBELLFIELD"}]},
        {"key": "CANTERBURY", "value": [{"pos": 2, "neg": 0, "neu": 0, "suburb": "CANTERBURY"}]},
        {"key": "CARLTON", "value": [{"pos": 3, "neg": 1, "neu": 3, "suburb": "CARLTON"}]},
        {"key": "CARLTON NORTH", "value": [{"pos": 2, "neg": 1, "neu": 7, "suburb": "CARLTON NORTH"}]},
        {"key": "CARNEGIE", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "CARNEGIE"}]},
        {"key": "CAROLINE SPRINGS", "value": [{"pos": 1, "neg": 0, "neu": 1, "suburb": "CAROLINE SPRINGS"}]},
        {"key": "CARRUM", "value": [{"pos": 2, "neg": 0, "neu": 0, "suburb": "CARRUM"}]},
        {"key": "CARRUM DOWNS", "value": [{"pos": 2, "neg": 0, "neu": 0, "suburb": "CARRUM DOWNS"}]},
        {"key": "CAULFIELD EAST", "value": [{"pos": 0, "neg": 1, "neu": 0, "suburb": "CAULFIELD EAST"}]},
        {"key": "CAULFIELD NORTH", "value": [{"pos": 1, "neg": 0, "neu": 4, "suburb": "CAULFIELD NORTH"}]},
        {"key": "CAULFIELD SOUTH", "value": [{"pos": 1, "neg": 0, "neu": 1, "suburb": "CAULFIELD SOUTH"}]},
        {"key": "CHADSTONE", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "CHADSTONE"}]},
        {"key": "CHELSEA", "value": [{"pos": 3, "neg": 0, "neu": 2, "suburb": "CHELSEA"}]},
        {"key": "CHELTENHAM", "value": [{"pos": 5, "neg": 0, "neu": 3, "suburb": "CHELTENHAM"}]},
        {"key": "CHIRNSIDE PARK", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "CHIRNSIDE PARK"}]},
        {"key": "CLARINDA", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "CLARINDA"}]},
        {"key": "CLAYTON", "value": [{"pos": 0, "neg": 1, "neu": 2, "suburb": "CLAYTON"}]},
        {"key": "CLAYTON SOUTH", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "CLAYTON SOUTH"}]},
        {"key": "CLIFTON HILL", "value": [{"pos": 9, "neg": 0, "neu": 15, "suburb": "CLIFTON HILL"}]},
        {"key": "COBURG", "value": [{"pos": 6, "neg": 1, "neu": 7, "suburb": "COBURG"}]},
        {"key": "COBURG NORTH", "value": [{"pos": 2, "neg": 0, "neu": 3, "suburb": "COBURG NORTH"}]},
        {"key": "COCKATOO", "value": [{"pos": 0, "neg": 1, "neu": 1, "suburb": "COCKATOO"}]},
        {"key": "COLDSTREAM", "value": [{"pos": 3, "neg": 0, "neu": 0, "suburb": "COLDSTREAM"}]},
        {"key": "COLLINGWOOD", "value": [{"pos": 6, "neg": 1, "neu": 15, "suburb": "COLLINGWOOD"}]},
        {"key": "CRAIGIEBURN", "value": [{"pos": 0, "neg": 0, "neu": 4, "suburb": "CRAIGIEBURN"}]},
        {"key": "CRANBOURNE", "value": [{"pos": 0, "neg": 1, "neu": 1, "suburb": "CRANBOURNE"}]},
        {"key": "CRANBOURNE EAST", "value": [{"pos": 0, "neg": 0, "neu": 3, "suburb": "CRANBOURNE EAST"}]},
        {"key": "CRANBOURNE NORTH", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "CRANBOURNE NORTH"}]},
        {"key": "CREMORNE", "value": [{"pos": 3, "neg": 1, "neu": 0, "suburb": "CREMORNE"}]},
        {"key": "CROYDON", "value": [{"pos": 5, "neg": 1, "neu": 1, "suburb": "CROYDON"}]},
        {"key": "CROYDON SOUTH", "value": [{"pos": 6, "neg": 2, "neu": 3, "suburb": "CROYDON SOUTH"}]},
        {"key": "DANDENONG", "value": [{"pos": 1, "neg": 0, "neu": 2, "suburb": "DANDENONG"}]},
        {"key": "DANDENONG SOUTH", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "DANDENONG SOUTH"}]},
        {"key": "DEANSIDE", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "DEANSIDE"}]},
        {"key": "DERRIMUT", "value": [{"pos": 3, "neg": 0, "neu": 4, "suburb": "DERRIMUT"}]},
        {"key": "DINGLEY VILLAGE", "value": [{"pos": 0, "neg": 1, "neu": 4, "suburb": "DINGLEY VILLAGE"}]},
        {"key": "DIXONS CREEK", "value": [{"pos": 4, "neg": 1, "neu": 3, "suburb": "DIXONS CREEK"}]},
        {"key": "DOCKLANDS", "value": [{"pos": 16, "neg": 4, "neu": 12, "suburb": "DOCKLANDS"}]},
        {"key": "DONCASTER EAST", "value": [{"pos": 1, "neg": 1, "neu": 0, "suburb": "DONCASTER EAST"}]},
        {"key": "DROMANA", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "DROMANA"}]},
        {"key": "DRUMMOND NORTH", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "DRUMMOND NORTH"}]},
        {"key": "EAST MELBOURNE", "value": [{"pos": 4, "neg": 1, "neu": 7, "suburb": "EAST MELBOURNE"}]},
        {"key": "EDITHVALE", "value": [{"pos": 1, "neg": 0, "neu": 2, "suburb": "EDITHVALE"}]},
        {"key": "ELSTERNWICK", "value": [{"pos": 0, "neg": 1, "neu": 5, "suburb": "ELSTERNWICK"}]},
        {"key": "ELTHAM", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "ELTHAM"}]},
        {"key": "ELTHAM NORTH", "value": [{"pos": 0, "neg": 1, "neu": 1, "suburb": "ELTHAM NORTH"}]},
        {"key": "ELWOOD", "value": [{"pos": 6, "neg": 0, "neu": 6, "suburb": "ELWOOD"}]},
        {"key": "ENDEAVOUR HILLS", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "ENDEAVOUR HILLS"}]},
        {"key": "EPPING", "value": [{"pos": 1, "neg": 1, "neu": 0, "suburb": "EPPING"}]},
        {"key": "FAIRFIELD", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "FAIRFIELD"}]},
        {"key": "FERNTREE GULLY", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "FERNTREE GULLY"}]},
        {"key": "FITZROY", "value": [{"pos": 12, "neg": 0, "neu": 6, "suburb": "FITZROY"}]},
        {"key": "FITZROY NORTH", "value": [{"pos": 6, "neg": 0, "neu": 2, "suburb": "FITZROY NORTH"}]},
        {"key": "FLEMINGTON", "value": [{"pos": 2, "neg": 0, "neu": 6, "suburb": "FLEMINGTON"}]},
        {"key": "FOOTSCRAY", "value": [{"pos": 1, "neg": 0, "neu": 5, "suburb": "FOOTSCRAY"}]},
        {"key": "FOREST HILL", "value": [{"pos": 2, "neg": 0, "neu": 0, "suburb": "FOREST HILL"}]},
        {"key": "FRANKSTON", "value": [{"pos": 14, "neg": 3, "neu": 16, "suburb": "FRANKSTON"}]},
        {"key": "GLADSTONE PARK", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "GLADSTONE PARK"}]},
        {"key": "GLEN HUNTLY", "value": []},
        {"key": "GLEN IRIS", "value": [{"pos": 1, "neg": 0, "neu": 3, "suburb": "GLEN IRIS"}]},
        {"key": "GLEN WAVERLEY", "value": [{"pos": 2, "neg": 0, "neu": 4, "suburb": "GLEN WAVERLEY"}]},
        {"key": "GLENROY", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "GLENROY"}]},
        {"key": "GREENSBOROUGH", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "GREENSBOROUGH"}]},
        {"key": "GREENVALE", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "GREENVALE"}]},
        {"key": "HADFIELD", "value": [{"pos": 2, "neg": 0, "neu": 0, "suburb": "HADFIELD"}]},
        {"key": "HALLAM", "value": [{"pos": 2, "neg": 0, "neu": 3, "suburb": "HALLAM"}]},
        {"key": "HAMPTON", "value": [{"pos": 2, "neg": 2, "neu": 2, "suburb": "HAMPTON"}]},
        {"key": "HAMPTON PARK", "value": [{"pos": 1, "neg": 0, "neu": 2, "suburb": "HAMPTON PARK"}]},
        {"key": "HAWTHORN", "value": [{"pos": 1, "neg": 0, "neu": 9, "suburb": "HAWTHORN"}]},
        {"key": "HAWTHORN EAST", "value": []},
        {"key": "HEALESVILLE", "value": [{"pos": 4, "neg": 0, "neu": 2, "suburb": "HEALESVILLE"}]},
        {"key": "HEIDELBERG WEST", "value": [{"pos": 2, "neg": 1, "neu": 2, "suburb": "HEIDELBERG WEST"}]},
        {"key": "HOPPERS CROSSING", "value": [{"pos": 1, "neg": 0, "neu": 4, "suburb": "HOPPERS CROSSING"}]},
        {"key": "HUGHESDALE", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "HUGHESDALE"}]},
        {"key": "HUNTINGDALE", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "HUNTINGDALE"}]},
        {"key": "IVANHOE EAST", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "IVANHOE EAST"}]},
        {"key": "KALLISTA", "value": [{"pos": 3, "neg": 0, "neu": 0, "suburb": "KALLISTA"}]},
        {"key": "KANGAROO GROUND", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "KANGAROO GROUND"}]},
        {"key": "KEALBA", "value": [{"pos": 2, "neg": 0, "neu": 0, "suburb": "KEALBA"}]},
        {"key": "KEILOR EAST", "value": [{"pos": 2, "neg": 0, "neu": 4, "suburb": "KEILOR EAST"}]},
        {"key": "KENSINGTON", "value": [{"pos": 0, "neg": 0, "neu": 6, "suburb": "KENSINGTON"}]},
        {"key": "KEW", "value": [{"pos": 2, "neg": 3, "neu": 19, "suburb": "KEW"}]},
        {"key": "KEW EAST", "value": [{"pos": 4, "neg": 0, "neu": 1, "suburb": "KEW EAST"}]},
        {"key": "KILMORE", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "KILMORE"}]},
        {"key": "KILSYTH", "value": [{"pos": 3, "neg": 0, "neu": 0, "suburb": "KILSYTH"}]},
        {"key": "KYABRAM SOUTH", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "KYABRAM SOUTH"}]},
        {"key": "LANGWARRIN", "value": [{"pos": 2, "neg": 0, "neu": 1, "suburb": "LANGWARRIN"}]},
        {"key": "LANGWARRIN SOUTH", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "LANGWARRIN SOUTH"}]},
        {"key": "LAVERTON", "value": [{"pos": 0, "neg": 1, "neu": 0, "suburb": "LAVERTON"}]},
        {"key": "LAVERTON NORTH", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "LAVERTON NORTH"}]},
        {"key": "LILYDALE", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "LILYDALE"}]},
        {"key": "MACLEOD", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "MACLEOD"}]},
        {"key": "MAIDSTONE", "value": [{"pos": 1, "neg": 1, "neu": 2, "suburb": "MAIDSTONE"}]},
        {"key": "MALVERN", "value": [{"pos": 4, "neg": 0, "neu": 4, "suburb": "MALVERN"}]},
        {"key": "MALVERN EAST", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "MALVERN EAST"}]},
        {"key": "MANOR LAKES", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "MANOR LAKES"}]},
        {"key": "MARIBYRNONG", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "MARIBYRNONG"}]},
        {"key": "MCKINNON", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "MCKINNON"}]},
        {"key": "MELBOURNE", "value": []},
        {"key": "MELBOURNE AIRPORT", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "MELBOURNE AIRPORT"}]},
        {"key": "MENTONE", "value": [{"pos": 4, "neg": 1, "neu": 5, "suburb": "MENTONE"}]},
        {"key": "MERNDA", "value": [{"pos": 2, "neg": 0, "neu": 1, "suburb": "MERNDA"}]},
        {"key": "MIDDLE PARK", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "MIDDLE PARK"}]},
        {"key": "MITCHAM", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "MITCHAM"}]},
        {"key": "MONBULK", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "MONBULK"}]},
        {"key": "MONT ALBERT NORTH", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "MONT ALBERT NORTH"}]},
        {"key": "MONTMORENCY", "value": [{"pos": 1, "neg": 0, "neu": 1, "suburb": "MONTMORENCY"}]},
        {"key": "MOONEE PONDS", "value": [{"pos": 0, "neg": 0, "neu": 4, "suburb": "MOONEE PONDS"}]},
        {"key": "MOORABBIN", "value": [{"pos": 1, "neg": 1, "neu": 2, "suburb": "MOORABBIN"}]},
        {"key": "MOOROODUC", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "MOOROODUC"}]},
        {"key": "MORDIALLOC", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "MORDIALLOC"}]},
        {"key": "MORNINGTON", "value": [{"pos": 2, "neg": 0, "neu": 10, "suburb": "MORNINGTON"}]},
        {"key": "MOUNT EVELYN", "value": [{"pos": 2, "neg": 0, "neu": 1, "suburb": "MOUNT EVELYN"}]},
        {"key": "MOUNT MARTHA", "value": [{"pos": 4, "neg": 0, "neu": 0, "suburb": "MOUNT MARTHA"}]},
        {"key": "MOUNT RICHMOND", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "MOUNT RICHMOND"}]},
        {"key": "MOUNT WAVERLEY", "value": [{"pos": 2, "neg": 2, "neu": 4, "suburb": "MOUNT WAVERLEY"}]},
        {"key": "MULGRAVE", "value": [{"pos": 1, "neg": 2, "neu": 2, "suburb": "MULGRAVE"}]},
        {"key": "MURRUMBEENA", "value": [{"pos": 0, "neg": 0, "neu": 3, "suburb": "MURRUMBEENA"}]},
        {"key": "NARRE WARREN", "value": [{"pos": 0, "neg": 0, "neu": 7, "suburb": "NARRE WARREN"}]},
        {"key": "NEWPORT", "value": [{"pos": 3, "neg": 0, "neu": 3, "suburb": "NEWPORT"}]},
        {"key": "NOBLE PARK", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "NOBLE PARK"}]},
        {"key": "NOBLE PARK NORTH", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "NOBLE PARK NORTH"}]},
        {"key": "NORTH MELBOURNE", "value": [{"pos": 3, "neg": 1, "neu": 11, "suburb": "NORTH MELBOURNE"}]},
        {"key": "NORTHCOTE", "value": [{"pos": 3, "neg": 1, "neu": 4, "suburb": "NORTHCOTE"}]},
        {"key": "NUNAWADING", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "NUNAWADING"}]},
        {"key": "OAK PARK", "value": [{"pos": 2, "neg": 0, "neu": 0, "suburb": "OAK PARK"}]},
        {"key": "OAKLEIGH EAST", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "OAKLEIGH EAST"}]},
        {"key": "OAKLEIGH SOUTH", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "OAKLEIGH SOUTH"}]},
        {"key": "OFFICER", "value": [{"pos": 2, "neg": 0, "neu": 1, "suburb": "OFFICER"}]},
        {"key": "OLINDA", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "OLINDA"}]},
        {"key": "PAKENHAM", "value": [{"pos": 1, "neg": 3, "neu": 7, "suburb": "PAKENHAM"}]},
        {"key": "PAKENHAM UPPER", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "PAKENHAM UPPER"}]},
        {"key": "PARKDALE", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "PARKDALE"}]},
        {"key": "PARKVILLE", "value": [{"pos": 1, "neg": 1, "neu": 9, "suburb": "PARKVILLE"}]},
        {"key": "PASCOE VALE", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "PASCOE VALE"}]},
        {"key": "PASCOE VALE SOUTH", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "PASCOE VALE SOUTH"}]},
        {"key": "PATTERSON LAKES", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "PATTERSON LAKES"}]},
        {"key": "POINT COOK", "value": [{"pos": 6, "neg": 0, "neu": 5, "suburb": "POINT COOK"}]},
        {"key": "PORT MELBOURNE", "value": [{"pos": 3, "neg": 1, "neu": 4, "suburb": "PORT MELBOURNE"}]},
        {"key": "PORTSEA", "value": [{"pos": 4, "neg": 0, "neu": 0, "suburb": "PORTSEA"}]},
        {"key": "PRAHRAN", "value": []},
        {"key": "PRESTON", "value": [{"pos": 3, "neg": 0, "neu": 4, "suburb": "PRESTON"}]},
        {"key": "RESEARCH", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "RESEARCH"}]},
        {"key": "RESERVOIR", "value": [{"pos": 2, "neg": 0, "neu": 2, "suburb": "RESERVOIR"}]},
        {"key": "RICHMOND", "value": [{"pos": 2, "neg": 1, "neu": 7, "suburb": "RICHMOND"}]},
        {"key": "RINGWOOD", "value": [{"pos": 8, "neg": 3, "neu": 1, "suburb": "RINGWOOD"}]},
        {"key": "RINGWOOD NORTH", "value": [{"pos": 0, "neg": 2, "neu": 0, "suburb": "RINGWOOD NORTH"}]},
        {"key": "ROKEWOOD", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "ROKEWOOD"}]},
        {"key": "ROSANNA", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "ROSANNA"}]},
        {"key": "ROWVILLE", "value": [{"pos": 2, "neg": 0, "neu": 0, "suburb": "ROWVILLE"}]},
        {"key": "RYE", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "RYE"}]},
        {"key": "SAFETY BEACH", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "SAFETY BEACH"}]},
        {"key": "SANDRINGHAM", "value": [{"pos": 3, "neg": 0, "neu": 1, "suburb": "SANDRINGHAM"}]},
        {"key": "SASSAFRAS", "value": [{"pos": 1, "neg": 0, "neu": 1, "suburb": "SASSAFRAS"}]},
        {"key": "SCORESBY", "value": [{"pos": 4, "neg": 1, "neu": 1, "suburb": "SCORESBY"}]},
        {"key": "SEABROOK", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "SEABROOK"}]},
        {"key": "SEAFORD", "value": [{"pos": 6, "neg": 2, "neu": 4, "suburb": "SEAFORD"}]},
        {"key": "SEAHOLME", "value": [{"pos": 1, "neg": 0, "neu": 1, "suburb": "SEAHOLME"}]},
        {"key": "SEDDON", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "SEDDON"}]},
        {"key": "SELBY", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "SELBY"}]},
        {"key": "SMITHS GULLY", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "SMITHS GULLY"}]},
        {"key": "SOMERVILLE", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "SOMERVILLE"}]},
        {"key": "SOUTH MELBOURNE", "value": [{"pos": 5, "neg": 0, "neu": 5, "suburb": "SOUTH MELBOURNE"}]},
        {"key": "SOUTH MORANG", "value": [{"pos": 1, "neg": 0, "neu": 2, "suburb": "SOUTH MORANG"}]},
        {"key": "SOUTH WHARF", "value": [{"pos": 0, "neg": 1, "neu": 3, "suburb": "SOUTH WHARF"}]},
        {"key": "SOUTH YARRA", "value": [{"pos": 10, "neg": 0, "neu": 5, "suburb": "SOUTH YARRA"}]},
        {"key": "SOUTHBANK", "value": [{"pos": 5, "neg": 0, "neu": 7, "suburb": "SOUTHBANK"}]},
        {"key": "SPOTSWOOD", "value": [{"pos": 0, "neg": 1, "neu": 2, "suburb": "SPOTSWOOD"}]},
        {"key": "SPRINGVALE", "value": [{"pos": 4, "neg": 0, "neu": 1, "suburb": "SPRINGVALE"}]},
        {"key": "SPRINGVALE SOUTH", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "SPRINGVALE SOUTH"}]},
        {"key": "ST ALBANS", "value": [{"pos": 1, "neg": 0, "neu": 3, "suburb": "ST ALBANS"}]},
        {"key": "ST KILDA", "value": []},
        {"key": "ST KILDA EAST", "value": [{"pos": 4, "neg": 3, "neu": 8, "suburb": "ST KILDA EAST"}]},
        {"key": "ST KILDA WEST", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "ST KILDA WEST"}]},
        {"key": "STRATHMORE HEIGHTS", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "STRATHMORE HEIGHTS"}]},
        {"key": "SUNBURY", "value": [{"pos": 1, "neg": 0, "neu": 1, "suburb": "SUNBURY"}]},
        {"key": "SUNSHINE", "value": [{"pos": 1, "neg": 0, "neu": 1, "suburb": "SUNSHINE"}]},
        {"key": "SUNSHINE NORTH", "value": [{"pos": 0, "neg": 1, "neu": 1, "suburb": "SUNSHINE NORTH"}]},
        {"key": "SUNSHINE WEST", "value": [{"pos": 0, "neg": 1, "neu": 0, "suburb": "SUNSHINE WEST"}]},
        {"key": "SURREY HILLS", "value": [{"pos": 8, "neg": 2, "neu": 7, "suburb": "SURREY HILLS"}]},
        {"key": "TARNEIT", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "TARNEIT"}]},
        {"key": "TAYLORS HILL", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "TAYLORS HILL"}]},
        {"key": "TAYLORS LAKES", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "TAYLORS LAKES"}]},
        {"key": "TEMPLESTOWE", "value": [{"pos": 1, "neg": 0, "neu": 1, "suburb": "TEMPLESTOWE"}]},
        {"key": "THORNBURY", "value": [{"pos": 1, "neg": 0, "neu": 1, "suburb": "THORNBURY"}]},
        {"key": "TOORAK", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "TOORAK"}]},
        {"key": "TOOTGAROOK", "value": [{"pos": 2, "neg": 0, "neu": 2, "suburb": "TOOTGAROOK"}]},
        {"key": "TULLAMARINE", "value": [{"pos": 1, "neg": 0, "neu": 3, "suburb": "TULLAMARINE"}]},
        {"key": "UPPER FERNTREE GULLY", "value": [{"pos": 2, "neg": 4, "neu": 12, "suburb": "UPPER FERNTREE GULLY"}]},
        {"key": "VERMONT", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "VERMONT"}]},
        {"key": "VERMONT SOUTH", "value": [{"pos": 0, "neg": 0, "neu": 3, "suburb": "VERMONT SOUTH"}]},
        {"key": "WANTIRNA", "value": [{"pos": 2, "neg": 0, "neu": 1, "suburb": "WANTIRNA"}]},
        {"key": "WANTIRNA SOUTH", "value": [{"pos": 0, "neg": 0, "neu": 2, "suburb": "WANTIRNA SOUTH"}]},
        {"key": "WARRANDYTE", "value": [{"pos": 1, "neg": 0, "neu": 1, "suburb": "WARRANDYTE"}]},
        {"key": "WERRIBEE", "value": [{"pos": 1, "neg": 5, "neu": 5, "suburb": "WERRIBEE"}]},
        {"key": "WERRIBEE SOUTH", "value": [{"pos": 2, "neg": 0, "neu": 1, "suburb": "WERRIBEE SOUTH"}]},
        {"key": "WEST FOOTSCRAY", "value": [{"pos": 1, "neg": 1, "neu": 0, "suburb": "WEST FOOTSCRAY"}]},
        {"key": "WEST MELBOURNE", "value": [{"pos": 1, "neg": 0, "neu": 3, "suburb": "WEST MELBOURNE"}]},
        {"key": "WHEELERS HILL", "value": [{"pos": 2, "neg": 0, "neu": 1, "suburb": "WHEELERS HILL"}]},
        {"key": "WILLIAMS LANDING", "value": [{"pos": 3, "neg": 0, "neu": 1, "suburb": "WILLIAMS LANDING"}]},
        {"key": "WILLIAMSTOWN", "value": [{"pos": 4, "neg": 0, "neu": 5, "suburb": "WILLIAMSTOWN"}]},
        {"key": "WILLIAMSTOWN NORTH", "value": [{"pos": 0, "neg": 0, "neu": 1, "suburb": "WILLIAMSTOWN NORTH"}]},
        {"key": "WINCHELSEA SOUTH", "value": [{"pos": 2, "neg": 0, "neu": 1, "suburb": "WINCHELSEA SOUTH"}]},
        {"key": "WINDSOR", "value": [{"pos": 9, "neg": 0, "neu": 3, "suburb": "WINDSOR"}]},
        {"key": "WOLLERT", "value": [{"pos": 1, "neg": 0, "neu": 0, "suburb": "WOLLERT"}]},
        {"key": "YARRAVILLE", "value": [{"pos": 1, "neg": 0, "neu": 2, "suburb": "YARRAVILLE"}]}
    ]
}
